### PR TITLE
Release 1.5

### PR DESCRIPTION
**Pull request by solegalli**
Hi @GLevV and @datacubeR 

I am planning to launch a new version of Feature-engine next Monday, which features your latest contributions.

Check the what's new if you want, and let me know if I forgot something.

Thanks a lot for your contributions to the package!

### CODE REVIEW

**Comment by solegalli** [comment]
Hi @david-cortes You also contributed code to this release, so looping you in, I am releasing a new version on Monday.

**Comment by GLevV** [comment]
String similarity example is not merged yet https://github.com/feature-engine/feature-engine-examples/pull/11

Also SSE needs a hotfix because base class changed

**Comment by solegalli** [comment]
@Morgan-Sell tagging you along as well, as we will release the information value selector on Monday!!

**Comment by datacubeR** [comment]
Hi @solegalli, I've been super busy in these last days because of Uni, but ready to keep helping. Thanks so much for letting me contribute to the package. Please feel free to add assign me to new PRs, now I have more time to dedicate to Feature Engine.

**Pull request merged**
