### PR TITLE
allow sample weight in shuffle features

### LINKED ISSUE #654: fit_params not supported for SelectByShuffling (documentation suggests it is supported)
**Describe the bug**
Documentation suggests that fit_params is supported for SelectByShuffling. But my tests suggest it is not supported. I have a working example below. Let me know if using incorrectly or if I can do any more tests to help.

**Working example without fit_params**

```import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from feature_engine.selection import SelectByShuffling

X = pd.DataFrame(dict(x1 = [1000,2000,1000,1000,2000,3000], x2 = [1000,2000,1000,1000,2000,3000]))
y = pd.Series([1,0,0,1,1,0])

sbs = SelectByShuffling(RandomForestClassifier(random_state=42), cv=2, random_state=42)
sbs.fit_transform(X, y)
```

**Example with fit_params not working**

```import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from feature_engine.selection import SelectByShuffling

X = pd.DataFrame(dict(x1 = [1000,2000,1000,1000,2000,3000], x2 = [1000,2000,1000,1000,2000,3000]))
y = pd.Series([1,0,0,1,1,0])

sbs = SelectByShuffling(RandomForestClassifier(random_state=42), cv=2, random_state=42)

sample_weight = [1000,2000,1000,1000,2000,3000]
fit_p = {"sample_weight": sample_weight}

sbs.fit_transform(X, y, **fit_p)
```

**Expected behaviour**

Expect for unpacked params within fit_params to be passed to underlying model / classifier

**Error log**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[9], line 1
----> 1 sbs.fit_transform(X, y, **fit_p)

File ~/Dev/litmus/.env/lib/python3.10/site-packages/sklearn/base.py:870, in TransformerMixin.fit_transform(self, X, y, **fit_params)
    867     return self.fit(X, **fit_params).transform(X)
    868 else:
    869     # fit method of arity 2 (supervised transformation)
--> 870     return self.fit(X, y, **fit_params).transform(X)

TypeError: SelectByShuffling.fit() got an unexpected keyword argument 'sample_weight'
```

**Desktop (please complete the following information):**

 - OS: Mac OS 13.2.1 (22D68)
 - Browser: Chrome
 - Version: 112.0.5615.49 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by solegalli**
closes #654

### CODE REVIEW

**Comment by solegalli** [comment]
Hey @markdregan

Here a PR to expand the fit method of Shuffle features to accommodate sample weights.

This is training the model with sample weights. The predictions done after shuffling are done without weighting. This is, based on my understanding, the correct procedure. Correct me if I am wrong.

Thank you!

**Comment by solegalli** [comment]
Looking at the cross_validate logic, the performance on test set is calculated without sample_weights:

https://github.com/scikit-learn/scikit-learn/blob/364c77e047ca08a95862becf40a04fe9d4cd2c98/sklearn/model_selection/_validation.py#L707-L711

Sample weights is used only to train:

https://github.com/scikit-learn/scikit-learn/blob/364c77e047ca08a95862becf40a04fe9d4cd2c98/sklearn/model_selection/_validation.py#L682-L686

**Comment by markdregan** [comment]
Thank you! I will test this week. 🙌

**Comment by markdregan** [comment]
TY. Confirmed working correctly. Thanks for the fast PR!

**Pull request merged**
